### PR TITLE
Project #1: Positioning and floating elements

### PR DESCRIPTION
**Pull request by NoTengoBattery**
Project # 1: Positioning and floating elements
===

This pull request will merge the project feature branch inside the main repository branch.

The main repository branch only contains the commit needed to make linters GitHub workflow. Inside the feature branch, you can find the whole project history. You can see the commit timeline inside the feature branch.

Do not hesitate to make suggestions, this project is open for improvements.

Live demo
===

Please take a look at [this](https://notengobattery.github.io/project-1/) link for a live demo of the project, hosted by GitHub pages.

### CODE REVIEW

**Comment by NoTengoBattery** [comment]
Please take into consideration that this source code is too "spaghetti" for my taste. This is probably fine because we are starting the program, I just want to let a record that I disagree with how complex it is at this point, I am aware of it and I am going to do better the next opportunity.

**Comment by NoTengoBattery** [comment]
I was checking the deployed webpage, and it does not load the font assets. Therefore, fonts will render bad inside the GitHub Pages but it should work if you run the page locally.

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
Hello @NoTengoBattery  and @AK-Devil  :wave: 
You guys have done amazing work on this project. It looks good and almost ready for approval.
- Nice readme and pull request message, and also I like how you left comments about the issues you faced.
There are still some little fixes you need to do before the project can be approved.
- [ ] Avoid the use of `!important` in your CSS. It is considered bad practice and you can read more about why it is considered bad practice [here](https://developer.mozilla.org/en/docs/Web/CSS/Specificity#:~:text=Using%20!,greater%20specificity%20will%20be%20applied.).
- [ ] your clone should contain links to other articles with image previews on the leftmost side and links to more popular articles on the rightmost side just as seen in the screenshot below.
Screenshot from 2020-11-26 01-04-39
- [ ] Your webpage should have an editors' pick aside section and you should use an aside tag for it.
Screenshot from 2020-11-26 01-09-43
- [ ] This project is about positioning elements and therefore you are required to use a combination of grid, flex, and float for positioning elements. So far you've only used flex. You can use float to position the editor's pick aside section and grid for the theory of inflation section.

Please request another review when you are done implementing the changes and good luck.
slack(@ebeagusamuel)

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
Hello @NoTengoBattery  and @AK-Devil :wave: 
You have made a nice improvement from the last review and have made most of the changes requested.
However, there are still some changes to be made 
- [x] Use an aside tag for the editor's pick section.
Screenshot from 2020-11-26 17-45-03
- [x] The images in the More in Space and Astronomy section is not loading and that could most probably be because of the way you are specifying the path to the image. Use an absolute path to point to the images i.e './assets/images/...'
Screenshot from 2020-11-26 17-37-45
Please do request another review once you are done making the changes
slack(@ebeagusamuel)

**Pull request merged**
